"""migtaition0.2

Revision ID: 11d0c6a64dc6
Revises: 9d4473b7cd47
Create Date: 2023-10-03 17:35:52.379479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11d0c6a64dc6'
down_revision: Union[str, None] = '9d4473b7cd47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'to_the_seller_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('review', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('review', 'review_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'review_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('review', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('review', 'to_the_seller_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
