"""check update

Revision ID: 2bf4c9a3a967
Revises: 0d8f0da92faa
Create Date: 2023-10-12 20:46:55.787022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf4c9a3a967'
down_revision: Union[str, None] = '0d8f0da92faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check', 'is_deleted')
    # ### end Alembic commands ###
