"""migtaition0.3

Revision ID: 99c606471e2a
Revises: fa534a44d9fd
Create Date: 2023-10-11 16:06:15.902867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c606471e2a'
down_revision: Union[str, None] = 'fa534a44d9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('products_basket', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_column('seller_product', 'price')
    op.add_column('seller_products_size', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('seller_products_size', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller_products_size', 'is_deleted')
    op.drop_column('seller_products_size', 'price')
    op.add_column('seller_product', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('products_basket', 'is_deleted')
    op.drop_column('brand', 'is_deleted')
    # ### end Alembic commands ###
