"""migtaition0.1

Revision ID: 9d4473b7cd47
Revises: 20a1ef17adc6
Create Date: 2023-10-03 17:34:24.064442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d4473b7cd47'
down_revision: Union[str, None] = '20a1ef17adc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_who_left_review_id', sa.Integer(), nullable=False),
    sa.Column('to_the_seller_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.String(), nullable=False),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.ForeignKeyConstraint(['to_the_seller_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_who_left_review_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_id'), 'review', ['id'], unique=False)
    op.add_column('seller_product', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('seller_product', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('seller_product', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller_product', 'deleted_at')
    op.drop_column('seller_product', 'created_at')
    op.drop_column('seller_product', 'is_deleted')
    op.drop_index(op.f('ix_review_id'), table_name='review')
    op.drop_table('review')
    # ### end Alembic commands ###
