"""check update

Revision ID: aa0c720b36db
Revises: 9616c390e5d6
Create Date: 2023-10-16 13:14:07.595535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa0c720b36db'
down_revision: Union[str, None] = '9616c390e5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discount_coupon', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('discount_coupon', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('discount_coupon', 'coupon_creation_date')
    op.drop_column('discount_coupon', 'coupon_delete_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discount_coupon', sa.Column('coupon_delete_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('discount_coupon', sa.Column('coupon_creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('discount_coupon', 'deleted_at')
    op.drop_column('discount_coupon', 'created_at')
    # ### end Alembic commands ###
