"""migtaition0.3

Revision ID: efe2d52d9561
Revises: 4baa7958dc08
Create Date: 2023-10-05 12:51:27.187535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe2d52d9561'
down_revision: Union[str, None] = '4baa7958dc08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_title', sa.String(), nullable=False),
    sa.Column('notification_text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_id'), 'notification', ['id'], unique=False)
    op.create_table('order_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(), nullable=False),
    sa.Column('notification_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['notification_status_id'], ['notification.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_id'), 'order_status', ['id'], unique=False)
    op.create_table('order_delivery_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('order_status_id', sa.Integer(), nullable=False),
    sa.Column('date_presentation_status', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['check.id'], ),
    sa.ForeignKeyConstraint(['order_status_id'], ['order_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_delivery_status_id'), 'order_delivery_status', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_delivery_status_id'), table_name='order_delivery_status')
    op.drop_table('order_delivery_status')
    op.drop_index(op.f('ix_order_status_id'), table_name='order_status')
    op.drop_table('order_status')
    op.drop_index(op.f('ix_notification_id'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
